export {default as HomePage} from './homePage/HomePage';
export {default as LoginPage} from './loginPage/LoginPage';
export {default as CartPage} from './cartPage/CartPage';
export {default as SearchPage} from './searchPage/SearchPage';
export {default as Register} from './register/Register';
export {default as AboutPage} from './aboutPage/AboutPage';
export {default as CheckoutPage} from './checkoutPage/CheckoutPage';
export {default as ContactPage} from './contactPage/ContactPage';
export {default as FavoritePage} from './favoritePage/FavoritePage';