export {MainCard, GalleryCard} from './cards/Cards';
export {BtnPrimary, BtnSecondary, BtnForm, BtnFormTable} from './button/Button';
export {Container, FormContaier, GridContainer, WidthContainer, BtnContaier} from './container/Container';
export {default as NavBar} from './navbar/NavBar';
export {default as NumbersBtn} from './numbersBtn/NumbersBtn';
export {FormInput, FieldInput, SelectedInput} from './inputs/Inputs';
export {MainHeading, MainHeadForm} from './Heads/Heads';
export {default as FormLink} from './formLink/FormLink';
export {default as Dropdown} from './dropdown/Dropdown';
export {default as TotalTable} from './totalTable/TotalTable';
export {default as Results} from './results/Results';
